- hosts: all
  become: yes

  tasks:

    - name: install system packages
      shell: "yes | aptdcon --hide-terminal --install 'build-essential'"

    # Default python is 3.6, just install some libs
    - name: install python packages
      pip:
        name:
          - NumPy, pandas, synapseclient
        executable: pip3

    - name: Install dependencies
      shell: "yes | aptdcon --hide-terminal --install 'build-essential gdebi-core zlib1g-dev libclang-dev libssl-dev libffi-dev libcurl4-openssl-dev libapparmor1 libssl1.0.0 libxml2-dev libjpeg-dev libpng-dev libfreetype6-dev libtiff5-dev libcairo2-dev libxt-dev bzip2 unixodbc unixodbc-dev'"

    - name: Add the CRAN apt key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: E298A3A825C0D65DFD57CBB651716619E084DAB9

    # R 3.6.3
    - name: Install R 3.6.3
      shell: "curl -O https://cdn.rstudio.com/r/ubuntu-1804/pkgs/r-3.6.3_1_amd64.deb && yes | gdebi r-3.6.3_1_amd64.deb"

    - name: Add R-Project apt repository
      shell: "aptdcon --add-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu {{ ansible_distribution_release }}-cran35/' && aptdcon --refresh"

    # Install R packages for R 3.6.3
    # - name: Install devtools
    #   shell: "/opt/R/3.6.3/bin/R -e \"install.packages('devtools', repos=c('https://cran.rstudio.com/'))\""

    # - name: Install synapser
    #   shell: "/opt/R/3.6.3/bin/R -e \"install.packages('synapser', repos=c('http://ran.synapse.org', 'https://cran.rstudio.com/'))\""

    # - name: Install tidyverse
    #   shell: "/opt/R/3.6.3/bin/R -e \"install.packages('tidyverse', repos=c('https://cran.rstudio.com/'))\""

    - name: Install shiny
      shell: "/opt/R/3.6.3/bin/R -e \"install.packages('shiny', repos=c('https://cran.rstudio.com/'))\""

    # - name: Install BiocManager
    #   shell: "/opt/R/3.6.3/bin/R -e \"install.packages('BiocManager', repos=c('https://cran.rstudio.com/'))\""

    # - name: Install RStudio Professional Drivers
    #   shell: "curl -O https://drivers.rstudio.org/7C152C12/installer/rstudio-drivers_1.6.0_amd64.deb && yes | gdebi rstudio-drivers_1.6.0_amd64.deb"

    # - name: Basic driver config
    #   shell: "cp /etc/odbcinst.ini /etc/odbcinst.ini.bak && cat /opt/rstudio-drivers/odbcinst.ini.sample | tee /etc/odbcinst.ini"

    # R 4.0.0
    - name: Install R 4.0
      shell: "curl -O https://cdn.rstudio.com/r/ubuntu-1804/pkgs/r-4.0.0_1_amd64.deb && yes | gdebi r-4.0.0_1_amd64.deb"

    - name: Add R-Project apt repository
      shell: "aptdcon --add-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu {{ ansible_distribution_release }}-cran40/' && aptdcon --refresh"

    # Install R packages for R 4.0.0
    # - name: Install devtools
    #   shell: "/opt/R/4.0.0/bin/R -e \"install.packages('devtools', repos=c('https://cran.rstudio.com/'))\""

    # - name: Install synapser
    #   shell: "/opt/R/4.0.0/bin/R -e \"install.packages('synapser', repos=c('http://ran.synapse.org', 'https://cran.rstudio.com/'))\""

    # - name: Install tidyverse
    #   shell: "/opt/R/4.0.0/bin/R -e \"install.packages('tidyverse', repos=c('https://cran.rstudio.com/'))\""

    - name: Install shiny
      shell: "/opt/R/4.0.0/bin/R -e \"install.packages('shiny', repos=c('https://cran.rstudio.com/'))\""

    # - name: Install BiocManager
    #   shell: "/opt/R/4.0.0/bin/R -e \"install.packages('BiocManager', repos=c('https://cran.rstudio.com/'))\""

    # - name: Install RStudio Professional Drivers
    #   shell: "curl -O https://drivers.rstudio.org/7C152C12/installer/rstudio-drivers_1.6.0_amd64.deb && yes | gdebi  rstudio-drivers_1.6.0_amd64.deb"

    # - name: Basic driver config
    #   shell: "cp /etc/odbcinst.ini /etc/odbcinst.ini.bak && cat /opt/rstudio-drivers/odbcinst.ini.sample | tee /etc/odbcinst.ini"

    # Symlink R 4.0.0
    - name: Symlink R 4.0.0
      shell: "ln -s /opt/R/4.0.0/bin/R /usr/local/bin/R && ln -s /opt/R/4.0.0/bin/Rscript /usr/local/bin/Rscript"

    # Install Shiny server Pro
    - name: Download Shiny Server
      shell: "wget https://s3.amazonaws.com/rstudio-shiny-server-pro-build/ubuntu-14.04/x86_64/shiny-server-commercial-1.5.13.1042-amd64.deb"

    - name: Install Shiny Server
      shell: "yes | gdebi shiny-server-commercial-1.5.13.1042-amd64.deb"
